# Generated by Django 6.0 on 2025-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('part_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voter_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['voter_id'],
                'indexes': [models.Index(fields=['voter_id'], name='voter_app_v_voter_i_1e3e48_idx'), models.Index(fields=['full_name'], name='voter_app_v_full_na_909944_idx'), models.Index(fields=['part_number'], name='voter_app_v_part_nu_f07a84_idx')],
            },
        ),
    ]
