# Generated by Django 6.0 on 2025-12-09 15:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('VJNT', 'Vimukta Jati Nomadic Tribes'), ('OTHER', 'Other')], max_length=10)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'castes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('total_members', models.IntegerField(default=1)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('family_type', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='SubCaste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcastes', to='voters.caste')),
            ],
            options={
                'db_table': 'subcastes',
                'ordering': ['name'],
                'unique_together': {('caste', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voter_photos/')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('epic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voters',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('education', models.CharField(blank=True, choices=[('ILLITERATE', 'Illiterate'), ('PRIMARY', 'Primary (1-4)'), ('MIDDLE', 'Middle (5-7)'), ('SECONDARY', 'Secondary (8-10)'), ('HSC', 'Higher Secondary (11-12)'), ('GRADUATE', 'Graduate'), ('POST_GRADUATE', 'Post Graduate'), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('LABOUR', 'Labour'), ('BUSINESS', 'Business'), ('SERVICE', 'Service'), ('STUDENT', 'Student'), ('HOUSEWIFE', 'Housewife'), ('RETIRED', 'Retired'), ('UNEMPLOYED', 'Unemployed'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('occupation_details', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_income', models.CharField(blank=True, choices=[('BELOW_1', 'Below 1 Lakh'), ('1_2', '1-2 Lakhs'), ('2_5', '2-5 Lakhs'), ('5_10', '5-10 Lakhs'), ('ABOVE_10', 'Above 10 Lakhs')], max_length=20, null=True)),
                ('party_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_party_member', models.BooleanField(default=False)),
                ('party_member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('political_inclination', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('twitter_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_divyang', models.BooleanField(default=False)),
                ('divyang_category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_government_employee', models.BooleanField(default=False)),
                ('no_of_children', models.IntegerField(default=0)),
                ('vehicle_ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('house_type', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_voting_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('voting_sincerity', models.CharField(blank=True, max_length=50, null=True)),
                ('polling_station_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=200, null=True)),
                ('data_verified', models.BooleanField(default=False)),
                ('last_verified_on', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_details', to='voters.voter')),
            ],
            options={
                'verbose_name_plural': 'Other Details',
                'db_table': 'other_details',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='voters.family')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='voters.voter')),
            ],
            options={
                'db_table': 'family_members',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_head', to='voters.voter'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('OFFICE', 'Office'), ('OTHER', 'Other')], default='PERMANENT', max_length=20)),
                ('house_no', models.CharField(max_length=50)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('village_town', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('assembly_constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('booth_no', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='voters.voter')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='VoterCaste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_caste_certificate', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('certificate_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voters.caste')),
                ('sub_caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voters.subcaste')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caste_info', to='voters.voter')),
            ],
            options={
                'db_table': 'voter_castes',
            },
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['voter_id'], name='voters_voter_i_70ce4c_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['last_name'], name='voters_last_na_7c2d45_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['mobile_number'], name='voters_mobile__fbdb56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'voter')},
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['surname'], name='families_surname_6ec29b_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['family_id'], name='families_family__d09598_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['voter', 'is_primary'], name='addresses_voter_i_7f7ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pincode'], name='addresses_pincode_6570d6_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['district', 'taluka'], name='addresses_distric_6b1c86_idx'),
        ),
    ]
